# Generated by Django 4.1.7 on 2023-05-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEtab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.CharField(max_length=50)),
                ('groupe', models.CharField(max_length=50)),
                ('fileName', models.CharField(max_length=100)),
            ],
        ),
    ]
